version: "3.7"

services:
  seanervinson-front-end-application:
    restart: always
    container_name: seanervinson-front-end-application
    image: seanervinson-front-end-application:latest
    build:
      context: .
      dockerfile: DockerFile
      labels:
        - "com.seanervinson.description=Front-End of seanervinson"
    ports:
      - "9000:80"
    networks:
      - seanervinson-front-network

networks:
  seanervinson-front-network:
    network_mode: bridge
    name: seanervinson-front-network
