FROM node:slim as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build
RUN rm -rf ./build
RUN rm -rf ./test
RUN rm -rf ./src
RUN rm -rf ./public

FROM nginx:alpine

COPY ./config/nginx/conf.d/default.conf /etc/nginx/conf.d/

COPY --from=builder /app/dist /app

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]